# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # ANCIENNE CONFIG
    # router:
    #     resource: "%kernel.root_dir%/config/routing.yml"
    #     strict_requirements: ~
    # form:            ~
    # csrf_protection: ~
    # validation:      { enable_annotations: false } #true avant install
    # #serializer:      { enable_annotations: true }
    # templating:
    #     engines: ['twig']
    # default_locale:  "%locale%"
    # trusted_hosts:   ~
    # session:
    #     # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    #     handler_id:  session.handler.native_file
    #     save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    # http_method_override: true
    # assets: ~
